### PR TITLE
Add intervention to remove PaymentRequest on CriOS M59

### PR DESCRIPTION
**Pull request by madmath**

### CODE REVIEW

**Comment by madmath** [comment]
cc @rsolomakhin for review

**Review by rsolomakhin — APPROVED** [review]

**Comment by madmath** [comment]
cc @gauntface to merge

**Comment by madmath** [comment]
Who handles deployment @gauntface ?

**Comment by gauntface** [comment]
@madmath Deployment should be automatic. If you aren't seeing it then please let me know.

**Comment by madmath** [comment]
It's been a while now and I still don't see https://storage.googleapis.com/prshim/v1/payment-shim.js updated with the new intervention.

**Comment by gauntface** [comment]
@madmath will chase up and figure out a way I can do this.

**Pull request merged**
